console.log("Welcome to tut 24");
let date=new Date();
// console.log(date);
let otherDate=new Date('8-4-2003 04:54:08');
// otherDate=new Date('June 13 1979');
// otherDate=new Date('9/05/2000');
console.log(otherDate);
let a=otherDate.getDay();
a=otherDate.getHours();
a=otherDate.getDate();
a=otherDate.getMinutes();
a=otherDate.getTime();
a=otherDate.getMonth();
otherDate.setDate(23);
otherDate.setFullYear(1923);
otherDate.setMinutes(33);
otherDate.setHours(3);
console.log(a);
console.log(otherDate);